# Generated by Django 5.0.6 on 2024-05-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='topping2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
